name: Release v4

on:
  push:
    branches:
      - main
    tags:
    - "v*"
    paths:
      - .github/workflows/docker-build-v4.yaml
      - .gpg/**
      - Dockerfile.v4

env:
  IMAGE_PATH: ${{ vars.IMAGE_PATH }}

jobs:
  # Push image to GitHub Packages.
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v6

    - name: Log in to GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Set image tag from Git ref
      run: |
        # Strip git ref prefix from version
        IMAGE_TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && IMAGE_TAG=$(echo $IMAGE_TAG | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$IMAGE_TAG" == "main" ] && IMAGE_TAG=latest

        echo "IMAGE_TAG=${IMAGE_TAG}" | tee -a $GITHUB_ENV

    - name: Build docker image
      run: make docker-build-v4

    - name: Push docker image
      run: make docker-push-v4
