name: PullRequest v4


on:
  push:
    paths:
      - .github/workflows/pr-v4.yaml
      - .gpg/**
      - Dockerfile.v4

  pull_request:
    paths:
      - .github/workflows/pr-v4.yaml
      - .gpg/**
      - Dockerfile.v4


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Build docker image
      run: make docker-build-v4
